### ISSUE TITLE
Enable media control

### ISSUE THREAD

**Issue by andrefilimono** [kslimani/clappr-google-ima-html5-preroll#10]
Hi! Thanks for the great plugin.
Is it possible to enable media controls while playing ads?
I want to handle some additional events such as expand/collapse, mute/unmute, pause/resume.

**Comment by kslimani** [comment]
@andrefilimono yes, you can even use your own custom controls while displaying video ad. (_keep in mind that controls may be not available on some iOS device in fullscreen mode_).

In this plugin, mediacontrols [are disabled](https://github.com/kslimani/clappr-google-ima-html5-preroll/blob/master/src/index.js#L93) to avoid user to seek/skip video ad.

Also note this plugin was written some times ago, and since, new Clappr release has now a `recycleVideo` playback option for mobile : some tricks used in this plugin are no longer needed and the code could be enhanced.

**Comment by andrefilimono** [comment]
But IMA SDK renders custom `<video>` element inside `<iframe>` (regardless of passed [opt_videoElement](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdDisplayContainer) in `google.ima.AdDisplayContainer`). So when I enable `mediaControl` it is already associated with video file given in the player config and play button starts main video not ad. 

But I have no ideas how to connect media controls to SDK`s video element, especially if it is a VPAID ad.

**Comment by kslimani** [comment]
You are correct about provided video element. This is one reason why i recommend using custom mediacontrol.

Google ima sdk expectation and behaviours may differs depending on if you are attempting to play advert on "desktop" or "mobile" device. (_because ad display requirements [differs on mobile](https://developers.google.com/interactive-media-ads/docs/sdks/html5/mobile_video)_).

You may be interested in [HTML5 IMA SDK sample source code](https://github.com/googleads/googleads-ima-html5).

**Comment by andrefilimono** [comment]
Thanks!
