### ISSUE TITLE
Not working with Clappr.FlasHLS plugin

### ISSUE THREAD

**Issue by AnanthKongu** [kslimani/clappr-google-ima-html5-preroll#8]
Hi, it's amazing but when I'm using it with clappr.flashls plugin it will not work

My plugin configuration:

plugins: {
                playback: [Clappr.FlasHLS],
                core: [LevelSelector, ClapprGoogleImaHtml5PrerollPlugin]
            },

**Comment by kslimani** [comment]
@AnanthKongu yes, like it is described on README, it support only Clappr playbacks which use an HTML5 video element.

I did that choice because, on mobile devices, the SDK use the provided player video element to play ad video banner.

Tough, on a "desktop" scenario, if browser has Flash plugin installed, then Google IMA will choose to display ad using Flash plugin. But this will only work on desktop, not on mobile devices. (_or maybe on some very old device with Flash plugin_).

I could add an option to "force" an to attempt to play advert event if there is no video element available. (_but i can't guarantee it will always work_).

Do you need me to implements such feature ?

**Comment by AnanthKongu** [comment]
ah! ok thanks for your attention, never mind :)
